### ISSUE TITLE
 “GWL_HINSTANCE”: 未声明的标识符

### ISSUE THREAD

**Issue by mengqunhan** [kimlongli/FiveChess#3]
GWL_HINSTANCE一直提示未定义的标识符，前面没有声明，也没有赋值。
`//创建上一步按钮
    
CreateWindow(L"BUTTON", L"上一步", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON,
        180, 645, 100, 40, hWndGlobal, (HMENU)IDB_PREVIOUS, (HINSTANCE)GetWindowLong(hWndGlobal, GWL_HINSTANCE), NULL);
//创建下一步按钮
    
CreateWindow(L"BUTTON", L"下一步", WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_DEFPUSHBUTTON,
        340, 645, 100, 40, hWndGlobal, (HMENU)IDB_NEXT, (HINSTANCE)GetWindowLong(hWndGlobal, GWL_HINSTANCE), `NULL);`

**Comment by kimlongli** [comment]
使用x86进行编译即可，别选x64

**Comment by kimlongli** [comment]
basic problem
